name: build ISO
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install Nix
        uses: nixbuild/nix-quick-install-action@v34
      - name: build the actual ISO
        run: nix build .
      - name: upload ISO as artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: recoveryos-nix.iso
          path: result/iso/*.iso
          if-no-files-found: error
        
